owncloud/announcementcenter

.travis.yml, README.md
=> Actually only testing travis

appinfo/app.php, appinfo/application.php, controller/pagecontroller.php, lib/notificationsnotifier.php, tests/appinfo/AppTest.php, tests/controller/PageControllerTest.php
=> Send notifications for announcements

controller/pagecontroller.php, css/style.css, js/script.js, templates/main.php, tests/controller/PageControllerTest.php
=> Issue 7 option to delete announcements

css/style.css
Caused by https://github.com/owncloud/core/pull/19611/files#r42214919
=> Fix emptycontent top margin

l10n/.tx/config, l10n/de.json, l10n/en.json, l10n/fr.json, l10n/l10n.pl, l10n/templates/announcementcenter.pot
=> Add De and Fr translations

l10n/ru.json
=> Add Russian from @SurovovOleg

appinfo/database.xml, appinfo/info.xml
=> Fix the maximum column size for MariaDB

.travis.yml, appinfo/database.xml, appinfo/info.xml
=> [8.2] Fix the maximum column size for MariaDB

lib/activityextension.php, tests/appinfo/AppTest.php, tests/appinfo/ApplicationTest.php, tests/controller/PageControllerTest.php, tests/lib/ActivityExtensionTest.php, tests/lib/ManagerTest.php
=> Better handling of linebreaks in the activity feed

appinfo/app.php
=> Add the second argument to registerNotifier

controller/pagecontroller.php, lib/notificationsnotifier.php, tests/appinfo/AppTest.php, tests/controller/PageControllerTest.php, tests/lib/NotificationsNotifierTest.php
=> OCP\Notification api is now public

lib/activityextension.php
=> Catch the exception that can be thrown as per the doc block

appinfo/app.php, js/script.js, lib/notificationsnotifier.php, tests/lib/NotificationsNotifierTest.php
Fix #58 
@gig13 can you test this?
=> Correctly use display name in notifications and when announcing

appinfo/app.php, appinfo/application.php, controller/pagecontroller.php, lib/backgroundjob.php, lib/manager.php, tests/appinfo/AppTest.php, tests/controller/PageControllerTest.php, tests/lib/BackgroundJobTest.php
@DeepDiver1975 mind to review? Thanks
=> Use callForAllUsers instead of creating a huge array

lib/notificationsnotifier.php, tests/lib/NotificationsNotifierTest.php
PS: @dragotin you didn't create an issue for this anywhere, did you?
=> Make sure that the notification API can deliver the full message

lib/notificationsnotifier.php, tests/lib/NotificationsNotifierTest.php
=> [9.0] Make sure that the notification API can deliver the full message

controller/pagecontroller.php, js/script.js, lib/manager.php, tests/controller/PageControllerTest.php
=> Issue 67 allow announcement scrolling

controller/pagecontroller.php, js/script.js, lib/manager.php, tests/controller/PageControllerTest.php
=> [9.0] Allow announcement scrolling

appinfo/info.xml
=> added website, bugs, repository

lib/Notification/Notifier.php
Fixes https://github.com/owncloud/announcementcenter/issues/85
=> Allow announcements without messages

.travis.yml
=> add PHP7.2 to stable10

composer.lock, tests/Unit/Activity/ExtensionTest.php, tests/Unit/AppInfo/AppTest.php, tests/Unit/BackgroundJobTest.php, tests/Unit/Controller/PageControllerTest.php, tests/Unit/Notification/NotifierTest.php
1) Adjust PHPUnit Framework namespace for PHPUnit6 
2) Update bamarni/composer-bin-plugin (v1.3.0)  (while we are here)
=> Php unit 5 to 6

.drone.starlark, .drone.yml
See https://github.com/owncloud/password_policy/pull/248 for a description.
This is the same code, with config for this repo. This repo has no JavaScript or acceptance tests.
=> Initial starlark drone config

.drone.starlark
1) support for `build()` pipeline
2) bugfix for default browser in acceptance tests
=> Update to latest drone starlark code

lib/BackgroundJob.php
- Fixes https://github.com/owncloud/announcementcenter/issues/89
- Fixes https://github.com/owncloud/enterprise/issues/3579
=> use absolute server url in notification creation

.drone.starlark, composer.json, composer.lock, tests/Unit/Activity/ExtensionTest.php, tests/Unit/AppInfo/AppTest.php, tests/Unit/AppInfo/ApplicationTest.php, tests/Unit/BackgroundJobTest.php, tests/Unit/Controller/PageControllerTest.php, tests/Unit/ManagerTest.php, tests/Unit/Notification/NotifierTest.php
Similar to https://github.com/owncloud/configreport/pull/121
Note: `phpunit.xml` is already good in this app.
Note: this app does not have acceptance tests - no Behat to adjust
=> Adjust tests

.drone.starlark, tests/Unit/AppInfo/AppTest.php, tests/Unit/AppInfo/RoutesTest.php, tests/Unit/Controller/PageControllerTest.php, tests/Unit/ManagerTest.php, tests/Unit/Notification/NotifierTest.php, vendor-bin/owncloud-codestyle/composer.json
like done in core https://github.com/owncloud/core/pull/36580
and apply latest drone starlark code changes
=> Coding standard 2.0.0

Makefile, lib/Activity/Extension.php, lib/Notification/Notifier.php, phpstan.neon, vendor-bin/phpstan/composer.json
Related - https://github.com/owncloud/QA/issues/642
Update phpstan to 0.12
=> [Tests-Only] Update phpstan to latest version

.drone.star
=> [Tests-Only] Run phpstan in CI

.drone.star, vendor-bin/phan/composer.json
Part of https://github.com/owncloud/QA/issues/643
This pr includes:
- phan update to 2.7
- phan in CI
=> [Tests-Only] Bump phan 2.7

phpstan.neon
For `phpstan` `0.12.26` onwards.
=> [Tests-Only] Adjust bootstrapFiles in phpstan.neon

.drone.star
from activity app.
The changes are all to acceptance testing, no there is no real difference for this app.
=> [tests-only] Implement latest .drone.star as at 2020-12-22

CHANGELOG.md, appinfo/info.xml, sonar-project.properties
=> Merge back release 1.2.2

.drone.star
- https://github.com/owncloud/QA/issues/707
=> [tests-only] Use owncloudci/wait-for docker image and used PHP 7.4

.drone.star, phpstan.neon, vendor-bin/phpstan/composer.json
Followup on #178
Related https://github.com/owncloud/QA/issues/707
=> Fixed unimplemented fn case and placements

lib/Notification/Notifier.php, templates/main.php, vendor-bin/owncloud-codestyle/composer.json, vendor-bin/phan/composer.json, vendor-bin/phpstan/composer.json
Apply owncloud coding-standard v4
=> [tests-only] [full-ci] owncloud coding-standard v4

.drone.star
Part of issue https://github.com/owncloud/QA/issues/818
=> [tests-only] Update CI
